### ISSUE TITLE
ROI file and filtered movie

### ISSUE THREAD

**Issue by tjoy20** [ackmanlab/pySEAS#2]
Thank you for this package. I was hoping if you could share how you generated the ROI file. I see that it takes in an ROI zip for the ICA decomposition. Another issue is that after I run the ica_project.py, I am not able to get a filtered movie with argument -s and -sf for saving images. Here is what I entered:
ica_project.py -f  <folder path> -e 062521_00 -d 0 -raw -s -sf -fn  
and this produces one file 062521_00_raw_ica.hdf5 ( the folder did not have the roi zip file)

Any help would be greatly appreciated, thank you!

**Comment by scweiser** [comment]
Rois are optional, and can be produced by saving a .zip file of a set of rois exported from FIJI/ ImageJ.

I'm assuming no errors were thrown when the video should have been saved?  
If no errors were listed, it is likely an issue with the way opencv compiled with the ffmpeg library.  If the mp4 cannot save, try the command again with the -avi flag enabled instead.  

Please let me know if this solves your issue!

**Comment by tjoy20** [comment]
Thank you for the response. I do get an error - AttributeError: 'Experiment' object has no attribute 'filtered' ( it faults at line 300  in ica_project.py ; filtered = exp.filtered
Is this filtered the same as in ica.py where it is defined as filtered = PCA_rebuild(components,
                           returnmeta=True,
                           include_noise=include_noise,
                           t_start=t_start,
                           t_stop=t_stop,
                           filter_mean=filter_mean)

When I added this to ica_project.py, there were no errors but it still doesn't create the video. I tried the -avi flag and no luck.

**Comment by scweiser** [comment]
Ah, my bad.  I had rearranged the code before making it public, and that was an untested feature.  Pull again and try now

**Comment by tjoy20** [comment]
Thanks Sydney. Is there a way to save the video as just a tiff stack? The - avi is not working for some reason and the default mp4 has issues with the ffmpeg compilation on my mac. I'm trying to fix this, but a tiff stack would actually work better for some of the downstream applications.

**Comment by scweiser** [comment]
Sorry I'm not sure how I didn't see this earlier.

All the functions are available for opening a hdf5 file and saving it as a tiff if you look through the available functions.  I threw a quick output together in the example script, you can now save a tiff output with -ft (--filteredtiff) flag is set.

**Comment by tjoy20** [comment]
Thanks so much! was also able to get the filtered hdf5 file and from there saving it as tiff.  No further issues.

**Comment by VyshnaviSK** [comment]
Hi, can you point me to the script/function which helps me save the hdf5 as tiff?

**Comment by scweiser** [comment]
Hi @VyshnaviSK , if you have run ica decomposition using `ica_project.py` in the examples folder, you can run it with the additional flag `-ft` or `--filteredtiff` to save the filtered movie as a tiff.  Is that what you're looking for?

**Comment by VyshnaviSK** [comment]
Hi, 
Yes I have run ica_project - but the files were deleted in an intermediate step to free up storage. I just have the final hdf5 files created after artifact removal. So I am trying to see if there is a way to retain/recreate the .tiff files without having to rerun ica_project and save me on a lot of time since I'd have to go through too much data.
Thanks!  
 
I was going through the documentation of ica_project and found this. 
does this work the same way?

```
filename = 'my_component_video1_raw_ica.hdf5' (created after using gui view_components)
filtered = seas.ica.rebuild(filename,
                            apply_mean_filter=True)
seas.video.save(filtered, 'components_in_tiff_form.tiff')
```

**Comment by scweiser** [comment]
hi @VyshnaviSK , the project code is actually designed so that if you use a folder and experiment name, it'll automatically load the experiment and skip the decomposition step if it has already been applied.

If you're already loading it in python in an interpreter, then yes that set of lines should work!  Let me know if you run into any issues with it.

**Comment by VyshnaviSK** [comment]
Yes, I think so far they have been working. Thank you so much!
